EsbjergCityShop/EsbjergCityShop/Controllers/GiftCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EsbjergCityShop.Models;
using Gateway;
using Gateway.Models;
using Gateway.ServiceGateways;

namespace EsbjergCityShop.Controllers
{
    public class GiftCardsController : Controller
    {
        private readonly GiftCardServiceGateway _gg = new Facade().GetGiftCardGateway();

        [HttpGet]
        public ActionResult CreateGiftCard()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGiftCard(double? amount)
        {
            if (amount.HasValue && amount != 0.0)
            {
                var newCard = new GiftCard();
                newCard.Amount = amount.Value;
                newCard.CardNumber = Guid.NewGuid().ToString();
                var cart = ShoppingCart.GetCart();
                cart.AddItemToCart(newCard);
            }
            return RedirectToAction("CreateGiftCard");

        }

        [HttpGet]
        public ActionResult GiftCardBalance()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GiftCardBalance(string cardNumber)
        {
            var giftCard = _gg.GetByCardNumber(cardNumber);
            return View(giftCard);
        }
    }
}

EsbjergCityShop/EsbjergCityShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EsbjergCityShop.Models;
using Gateway.Models;

namespace EsbjergCityShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult CartIndex()
        {
            var cart = ShoppingCart.GetCart();
            return PartialView(cart);
        }

        public ActionResult RemoveItemFromCart(string cardNumber)
        {
            var cart = ShoppingCart.GetCart();
            cart.RemoveItemFromCart(cardNumber);
            return Redirect(Request.UrlReferrer.ToString());
        }

    }
}

EsbjergCityShop/EsbjergCityShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="background">
        <img src="~/Content/Images/bg/2.jpg" />
    </div>
    @*<-- Navbar -->*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Home/Index"><img src="~/Content/Images/logo.png" class="logo" /></a></li>
                    <li style="font-size: 18px">@Html.ActionLink("Køb Gavekort", "CreateGiftCard", "GiftCards")</li>
                    <li style="font-size: 18px">@Html.ActionLink("Check Gavekort Saldo", "GiftCardBalance", "GiftCards")</li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.Action("CartIndex", "ShoppingCart")</li>
                </ul>
                <span style="font-size: 18px">@Html.Partial("_LoginPartial")</span>
            </div>
        </div>
    </div>
    @*</-- Navbar -->*@
    <div class="content-wrapper">
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>
    @*<-- Footer -->*@
    <footer>
        <div class="container">
            @*google maps API*@
            <div class="row footer-container">
                <div class="col-md-4 google_map">
                    <h3 style="font-size: 20px">Find City-kontoret her!</h3>
                    <iframe width="90%" height="200px" style="border: 0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ3_ftLCshS0YRxxztk04CV_4&key=AIzaSyB8QxMxSvt6fc79RrYtL9QtCtEIOUnWOZo" allowfullscreen></iframe>
                </div>
                @*Åbningstider*@
                <div class="col-md-4">
                    <h3 style="font-size: 20px">City-kontorets Åbningstider</h3>
                    <table class="table-openinghours">
                        <tr>
                            <td>Mandag&nbsp;</td>
                            <td>&nbsp;kl. 10.00 til kl. 16.00</td>
                        </tr>
                        <tr>
                            <td>Tirsdag&nbsp;</td>
                            <td>&nbsp;kl. 10.00 til kl. 16.00</td>
                        </tr>
                        <tr>
                            <td>Onsdag&nbsp;</td>
                            <td>&nbsp;kl. 10.00 til kl. 16.00</td>
                        </tr>
                        <tr>
                            <td>Torsdag&nbsp;</td>
                            <td>&nbsp;kl. 10.00 til kl. 16.00</td>
                        </tr>
                        <tr>
                            <td>Fredag&nbsp;</td>
                            <td>&nbsp;kl. 10.00 til kl. 15.30</td>
                        </tr>
                    </table>
                </div>
                @*Specielle åbningstider*@
                <div class="col-md-4 opening_hours">
                    <h3 style="font-size: 20px">Specielle åbningstider i butikker</h3>
                    <table>
                        <tr>
                            <td>Lørdag den 26. marts - Påskelørdag - Åbent 10 - 15</td>
                        </tr>
                        <tr>
                            <td>Fredag den 29. april - LATE NIGHT - Åbent til kl. 22</td>
                        </tr>
                        <tr>
                            <td>Torsdag den 21. april - Åbent til kl. 18.00</td>
                        </tr>
                        <tr>
                            <td>Fredag den 3. juni – MIDNATSÅBENT til kl. 24.00</td>
                        </tr>
                        <tr>
                            <td>Fredag den 30. sep - Late Night - Åbent til kl. 22.00</td>
                        </tr>
                        <tr>
                            <td>Fredag den 25. nov - Black Christmas Friday & Juletræstænding - Late Night - Åbent til kl. 22</td>
                        </tr>
                    </table>
                </div>
            </div>
            <br />
        </div>
    </footer>
    @*</-- Footer -->*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="/Scripts/snowFall.min.jquery.js"></script>
    <script>
        $(function () {
            $("div.background").snowfall({
                flakeCount: 50,
                minSize: 1,
                maxSize: 4
            });
        });
    </script>
</body>
</html>